# [Required]
# Basic component information
repo: react-squirrel-backend
organization: ad-build-test
url: https://github.com/ad-build-test/react-squirrel-backend
description: test react-squirrel-backend

# [Required]
# Continous integration
approvalRule: all
testingCriteria: all
issueTracker: github
jiraProjectKey: n/a

# [Required]
# Type of deployment
# Types: [ioc, hla, tools, matlab, pydm, container]
deploymentType: container

# [Optional] 
# Build method for building the component
# Can be a simple command like 'make'
# build: 

# [Optional]
# Environments this app runs on
# environments:

# [Optional]
# Directories and files needed to run application
# runtimeDependencies:
